name: Build and Release

on:
  push:
    tags:
      - 'v*'

# Add permissions for creating releases
permissions:
  contents: write
  packages: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup CI environment
        run: |
          make install-deps

      - name: Build Linux version
        run: |
          make build-linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: |
            dist/efd-unpacker-*-linux-portable.zip
            dist/efd-unpacker-*-linux-portable.tar.gz
            dist/efd-unpacker-*-linux.AppImage
            dist/efd-unpacker-*-linux*.deb
            dist/efd-unpacker-*-linux*.rpm

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup CI environment
        run: |
          make install-deps

      - name: Build Windows version
        run: |
          make build-windows

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: |
            dist/efd-unpacker-*-windows-portable.zip
            dist/efd-unpacker-*-windows.msi

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup CI environment
        run: |
          make install-deps

      - name: Build macOS version
        run: |
          make build-macos

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-builds
          path: |
            dist/efd-unpacker-*-macos-portable.zip
            dist/efd-unpacker-*-macos.dmg

  # create-release:
  #   needs: [build-linux, build-windows, build-macos]
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.ref, 'refs/tags/')
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0  # Нужно для получения истории коммитов

  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: artifacts

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11'

  #     - name: Create version and generate release notes
  #       id: release_notes
  #       run: |
  #         make create-version
  #         make generate-release-notes
  #         echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
  #         cat release_notes.md >> $GITHUB_OUTPUT
  #         echo "EOF" >> $GITHUB_OUTPUT

  #     - name: Create Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: ${{ github.ref_name }}
  #         name: EFD Unpacker $(cat version.txt)
  #         body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
  #         draft: false
  #         prerelease: false
  #         files: |
  #           artifacts/linux-builds/*
  #           artifacts/windows-builds/*
  #           artifacts/macos-builds/*
